apiVersion: v1
kind: Service
metadata:
  name: loki-ingest
  labels:
    app.kubernetes.io/name: loki
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: loki
