apiVersion: v1
kind: Service
metadata:
  name: loki-query
  labels:
    app.kubernetes.io/name: loki
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9096
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/name: loki
