apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentbit
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      serviceAccountName: fluentbit
      terminationGracePeriodSeconds: 25
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: fluentbit
        image: docker.io/fluent/fluent-bit
        command:
        - /fluent-bit/bin/fluent-bit
        - -c
        - /fluent-bit/etc/fluent-bit.conf
        env:
        - name: LOG_LEVEL
          value: debug
        - name: MEM_BUF_LIMIT
          value: 5MB
        ports:
        - name: http
          containerPort: 2020
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
        volumeMounts:
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: db
          mountPath: /var/run/fluentbit
        - name: config
          mountPath: /fluent-bit/etc
        # - mountPath: /etc/machine-id
        #   name: etcmachineid
        #   readOnly: true
      volumes:
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: db
        hostPath:
          path: /var/run/fluentbit
      # - name: etcmachineid
      #   hostPath:
      #     path: /etc/machine-id
      #     type: File
      - name: config
        configMap:
          name: fluentbit
