apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

images:
- name: docker.io/fluent/fluent-bit
  newTag: 1.8.3@sha256:10ea2709cef6e7059d980b4969d5f9d753ef97278a817c214cbe9120b1152082

commonLabels:
  app.kubernetes.io/name: fluentbit

resources:
- ../rbac
- fluentbit-daemonset.yaml

configMapGenerator:
- name: fluentbit
  files:
  - fluent-bit.conf
  - parser-cri.conf
  - input-kubernetes.conf
  - filter-kubernetes.conf
  - parsers.conf
  - outputs.conf
